name: Code Style

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    name: Check & Fix Code Style

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Check code style
        run: ./vendor/bin/pint --test

      - name: Annotate code style issues
        if: failure()
        run: |
          echo "::error::Code style issues found. Run 'composer pint' locally to fix them."