name: Package Installation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  installation-test:
    runs-on: ubuntu-latest
    name: Test Package Installation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: none

    - name: Validate composer.json
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Check autoloading
      run: composer dump-autoload --optimize

    - name: Run basic tests
      run: |
        if [ -f "vendor/bin/phpunit" ]; then
          vendor/bin/phpunit tests/Unit/ --verbose
        else
          echo "PHPUnit not available, skipping tests"
        fi

    - name: Check code style
      run: |
        if [ -f "vendor/bin/pint" ]; then
          vendor/bin/pint --test
        else
          echo "Laravel Pint not available, skipping style check"
        fi